// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIjKfLXstwkA0ZyC5OqQ6fjhGFVvRhYog',
    appId: '1:408249445144:web:232d5ec54bbb4a19148c6d',
    messagingSenderId: '408249445144',
    projectId: 'av-root-23',
    authDomain: 'av-root-23.firebaseapp.com',
    databaseURL: 'https://av-root-23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'av-root-23.appspot.com',
    measurementId: 'G-9K0TRXVC3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmdLLHyphvWN_q0PNN9nDFcmru-dHdhuk',
    appId: '1:408249445144:android:c8d8a069b3459294148c6d',
    messagingSenderId: '408249445144',
    projectId: 'av-root-23',
    databaseURL: 'https://av-root-23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'av-root-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwbXv56Ma42y6jVh7yzlsJLxFzwNYwHBw',
    appId: '1:408249445144:ios:77c28d3f083ca54b148c6d',
    messagingSenderId: '408249445144',
    projectId: 'av-root-23',
    databaseURL: 'https://av-root-23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'av-root-23.appspot.com',
    iosBundleId: 'com.example.avRootApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwbXv56Ma42y6jVh7yzlsJLxFzwNYwHBw',
    appId: '1:408249445144:ios:60d205763a5e0964148c6d',
    messagingSenderId: '408249445144',
    projectId: 'av-root-23',
    databaseURL: 'https://av-root-23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'av-root-23.appspot.com',
    iosBundleId: 'com.example.avRootApp.RunnerTests',
  );
}
